# Lista oficial de produtos, que será usada para correção automática

produtos_oficiais = [
    "Molho Grill 1,05kg",
    "Molho Barbecue 1,05kg",
    "Molho Chipotle 1,05kg",
    "Ketchup Real 1,05kg",
    "Maionese Heinz 215g",
    "Mostarda Heinz Mel 220g",
    "Molho Tártaro 1,05kg",
    "Molho Alho e Ervas 215g",
    "Ketchup Heinz Curry 397g",
    "Molho Americano 1,05kg",
    "Molho Picante 1,05kg",
    "Molho Buffalo Wings 270ml",
    "Mostarda Hemmer 1kg",
    "Maionese Hemmer 1kg",
    "Ketchup Hemmer 1kg",
    "Fumaça Líquida RN 100ml",
    "Tempero para hambúrguer RN 150g",
    "Tempero para hambúrguer RN 100g",
    "Ketchup Heinz Picles 397g",
    "Ketchup Heinz Curry 397g",
    "Maionese Heinz 390g",
    "Ketchup Heinz 260g",
    "Maionese Alho e Ervas 215g",
    "Mostarda Escura Heinz 235g",
    "Ketchup Original Heinz 1,033kg",
    "Ketchup Bacon Heinz 397g",
    "Ketchup Picante Heinz 397g",
    "Tapioca Akio 500g",
    "Molho de Alho Roxo",
    "Molho de Alho com Ervas",
    "Molho de Alho Spicy Grill",
    "Geleia Cebola Caramelizada Bom Princípio 250g",
    "Geleia Morango com Pimenta Bom Princípio 250g",
    "Geleia Abacaxi com Pimenta Bom Princípio 250g",
    "Geleia de Pimenta Vermelha Bom Princípio 250g",
    "Pimenta Biquinho Sabor Silvestre 200g",
    "Creme de Pimenta Sabor Silvestre 270ml",
    "Molho de Pimenta Extra Forte Cepera 270ml",
    "Molho de Pimenta Sriracha Cepera 270ml",
    "Molho de Pimenta Buffalo Wings Cepera 270ml",
    "Cebola Caramelizada Natural Liam Alimentos 250g"
]
