# Lista oficial de produtos, que será usada para correção automática

produtos_oficiais = [
    "Alhonese Junior 1,1 Kg",
    "Alhonese Junior 350 g",
    "Baconnaise Junior 1,1 Kg",
    "Baconnaise Junior 360g",
    "Barbecue Junior 380g",
    "Cheddar Vegano Junior 1,1 Kg",
    "Cheddar Vegano Junior 350g",
    "Chiminese Junior 350 g",
    "Cx Baconnaise Junior 1,01 Kg",
    "Cx Maionese Grill Junior 1,01 Kg",
    "Dijonese Trufada Junior 360g",
    "Ketchup Americano Junior 1,1kg",
    "Ketchup Americano Junior 380g",
    "Ketchup Defumado Junior 1,01kg",
    "Ketchup Defumado Junior 380g",
    "Ketchup Trad. Junior 1,1 Kg",
    "Ketchup Trad. Junior 350g",
    "Maionese Caseira Junior 1,1 Kg",
    "Maionese Grill Junior 350g",
    "Maionese Grill Junior 1,1 Kg",
    "Maionese Junior 1,1 Kg",
    "Maionese Temperada Junior 1,1 Kg",
    "Maionese Trad. Junior 380g",
    "Molho Barbecue Junior 1,1 Kg",
    "Molho Chipotle Junior 1,01kg",
    "Molho Chipotle Junior 350g",
    "Molho do Cheff Junior 1,1 Kg",
    "Molho Ranch Junior 1,1 Kg",
    "Molho Sweet Chilli Junior 1,1 Kg",
    "Mostarda e Mel Junior 1,1kg",
    "Mostarda e Mel Junior 400g",
    "Mostarda Junior 1,1 Kg",
    "Mostarda Junior 190g",
    "Cx Maionese Temperada 1,01 Kg Zafran",
    "Cx Molho Americano 1,01 Kg Zafran",
    "Cx Molho Grill 1,01 Kg Zafran",
    "Ketchup Real Zafran 1,05 Kg",
    "Maionese Real Zafran 1,05 Kg",
    "Maionese Showy Paprika Zafran 1,05 Kg",
    "Maionese Temperada Zafran 1,05 Kg",
    "Molho Americano Zafran 1,05 Kg",
    "Molho Barbecue Zafran 1,05 Kg",
    "Molho Cebola Caramelizada Zafran 1,05 Kg",
    "Molho Chipotle Zafran 1,05 Kg",
    "Molho Grill Zafran 1,05 Kg",
    "Molho Grill Zafran 200g",
    "Molho Tartaro Zafran 1,05 Kg",
    "Molho Thai Sweet Chili Zafran 245g",
    "Molho Zafran Thai Sweet Chili 1,05 Kg",
    "Billy & Jack Bacon 1,01 Kg",
    "Billy & Jack Molho Verde 1 Kg",
    "Billy & Jack Original 1,01 Kg",
    "Billy & Jack Original 200g",
    "Billy & Jack Sabor Cheddar 1,01 Kg",
    "Billy & Jack Verde 355g",
    "Cx Billy & Jack Bacon 1,1 Kg",
    "Cx Billy & Jack Cheddar 1,1 Kg",
    "Cx Billy & Jack Original 1,1 Kg",
    "Cx Billy & Jack Taaty 1,1 Kg",
    "Cx Maionese Ki Sabor 1,01 Kg",
    "Cx Molho Tartaro 1,01 Kg",
    "Maionese Alho e Ervas Kisabor 1 Kg",
    "Maionese Tradicional Kisabor 1Kg",
    "Molho Tartaro Kisabor 1 Kg",
    "Molho Tartaro Kisabor 200g",
    "Barbecue Heinz 260g",
    "Ketchup Bacon 350g Cepera",
    "Ketchup com Curry Heinz 397 g Tomato",
    "Ketchup Do Assador Cepera 250g",
    "Ketchup Heinz 260 g",
    "Ketchup Original 400g Cepêra",
    "Ketchup Picante Cepera 400g",
    "Ketchup Picles 350g Cepêra",
    "Ketchup Sabor Bacon & Cebola Caramelizada Heinz 397g Tomato",
    "Ketchup Sabor Picante Heinz 397g",
    "Ketchup Sabor Picles Heinz 397 g Tomato",
    "Ketchup Tradicional Cepera 400g",
    "Ketchup Tradicional Quero 200g",
    "Ketchup Tradicional Quero 400g",
    "Maionese Churrasco Cepera 200g",
    "Maionese Heinz 215g",
    "Maionese Heinz 390g",
    "Maionese Heinz Alho tostado C/ Ervas 215g",
    "Maionese Saude 500g",
    "Maionese Tradicional Cepera 200g",
    "Maionese Verde 200g Cepera",
    "Molho Barbecue Cepera 400g",
    "Molho Barbecue Quero 210g",
    "Molho Cremoso Alho C/Limão 150ml Nobre Sabor",
    "Molho Cremoso de Alho Defumado 150ml Nobre Sabor",
    "Molho de Goiaba C/Pimenta do Assador 250g Cepêra",
    "Molho de Pimenta Buffalo Wings 270 ML Cepera",
    "Molho de Pimenta Sriracha 270 ML Cepera",
    "Molho Inglês 150ml Cepera",
    "Mostarda Amarela Cepera 370g",
    "Mostarda Mel Heinz 220g",
    "Pimenta Sabor Silvestre 270 Ml",
    "Cx Maionese Grill 1,1 Kg Bom Sabor",
    "Ketchup Cepêra 1,01kg",
    "Ketchup Original Heinz 1,033 Kg Tomato",
    "Ketchup Tradicional Hemmer 1 Kg",
    "Maionese Grill 1,1 Kg Bom Sabor",
    "Maionese Hemmer Tradicional 930g",
    "Maionese Saude 1 Kg",
    "Molho Barbecue Cepera 1,01kg",
    "Molho de Pimenta Ekma 1,01KG",
    "Molho do Chefe Bom Sabor 1,1Kg",
    "Mostarda Amarela Cepêra 1,01kg",
    "Mostarda Americana Hemmer 1 Kg",
    "Mostarda Ekma 950g",
    "Barbecue Cepera 3,5kg",
    "Ketchup Tradicional Cepera 3,5kg",
    "Maionese Saude 3 Kg",
    "Mostarda Amarela Cepêra 3,3kg",
    "Mostarda Ekma 3,3 Kg",
    "Guardanapo Sache Grampel 1000 Folhas",
    "Ketchup Heinz Sache (7g x 144 un)",
    "Ketchup Junior Sache (7g x 168un)",
    "Ketchup Sache Bom Sabor (7g x 182un)",
    "Maionese Bom Sabor Sache (7g x 182un)",
    "MAIONESE EKMA SACHÊ (7g x 168un)",
    "Maionese Heinz Sache (7g x 144un)",
    "Maionese Junior Sache (8g x 176un)",
    "Mostarda Ekma Sache (7g x 168un)",
    "Mostarda Heinz Sache (5g x 144un)",
    "Mostarda Junior Sache (7g x 176un)",
    "Mostarda Sache Bom Sabor (7g x 182un)",
    "Sache Azeite Junior 200 UND",
    "Sache Barbecue Cepera (175 un)",
    "Sache Billy Jack (7g x 168un)",
    "Sache Ketchup Cepera 154X7g",
    "Sache Ketchup Hellmanns ( 7g ) 168 Und",
    "Sache Maionese Cepera (175 un)",
    "Sache Maionese Hellmanns ( 7g ) 168 Und",
    "Sache Molho Pimenta Cepera (175 un)",
    "Sache Mostarda Cepera (175 un)",
    "Sache Mostarda Hellmanns ( 7 g ) 168 Und",
    "Sache Pimenta Junior 252Uni",
    "Molho Cremoso de Alho 150g Nobre Sabor",
    "Molho Cremoso de Pimenta Defumada 150g",
    "Pão Brioche Classico 65g (Bimbo)",
    "Pão Brioche Max 85g (Bimbo)",
    "Pão Madero 400g",
    "Pão Monaco C/Gergelim 75g (Bimbo)",
    "Pão Monaco Tradicional 75g (Bimbo)",
    "Pão Riviera C/Gergelim 65g (Bimbo)",
    "Pão Riviera Trad. 65g (Bimbo)",
    "Pão Supremo C/Gergelim 73g CD (Bimbo)",
    "Cx Pita Australiano 320g",
    "Cx Pita Brioche 480g",
    "Cx Pita Brioche 50g",
    "Cx Pita Brioche Duo 480g",
    "Cx Pita Corte Duplo 480g",
    "Cx Pita Extra Big c/ Gerg.",
    "Cx Pita Extra Big Trad. 200g",
    "Cx Pita Gergelim 480g",
    "Cx Pita Gergelim 50g",
    "Cx Pita Tradicional 480g",
    "Pita Bread Australiano 320g (4 und)",
    "Pita Bread Brioche 480g (6 und)",
    "Pita Bread Brioche 50g (6 und)",
    "Pita Bread Corte Duplo 480g (6 und)",
    "Pita Bread Extra Big C/Gergelim 200g (2 und)",
    "Pita Bread Extra Big Tradicional 200g (2 und)",
    "Pita Bread Gergelim 480g (6 und)",
    "Pita Bread Gergelim 50g (6 und)",
    "Pita Bread Tradicional 480g (6 und)",
    "Pita Brioche Duo 480 g (6 und)",
    "Pão de Hot Dog Max Bread 80g",
    "Pão Dog RN 75g",
    "Pão Dogão Joia Gergelim 110g",
    "Pão Dogão Parmesão RN 110g",
    "Pão Dogão RN C/Gergelim 120g",
    "Pão Dogão Tradicional RN 110g",
    "Pão Big Muzi C/Gergelim 90g 10 uni.",
    "Pão Muzi Black 75g 6 uni",
    "Pão Muzi Mesclado 75g 6 uni.",
    "Pão Muzi Red 75g 6 uni.",
    "Cx Max Bread Brioche 320g",
    "Cx Max Bread Gergelim 320g",
    "Pão Brioche Max Bread 320g (4 Und)",
    "Pão Gergelim Max Bread 320g (4 Und)",
    "Pão Mini Azul Lá Linda 330g",
    "Pão Mini Cebola Roxa La Linda 330g",
    "Pão Mini Pimenta Biquinho Lá Linda 330g",
    "Pão Mini Provolone Lá Linda 330g",
    "Acoplado Laminado Thermo Paper (250 und)",
    "Bisnaga p/ Molho 1L",
    "Box Lanche Peq. (50 Und)",
    "Embalagem Batata Delivery PDV (100un)",
    "Embalagem Batata Preta Aberta PDV (100un)",
    "Embalagem Batata Verde PDV (100un)",
    "Embalagem Lanche Box Colorida PDV (50un)",
    "Embalagem Lanche G Box Preta PDV (50un)",
    "Embalagem P/ Dogão 30X18 (260 Und)",
    "Embalagem P/ Doguinho 25X18 (310 Und)",
    "Embalagem TH 01 100 Und",
    "Embalagem TH 03 100 Und",
    "Embalagem TH 101 100 Und",
    "Embalagem TH 102 100 Und",
    "Embalagem TH-02 100 Und",
    "Lacre de Segurança Preto Rolo 500 Und",
    "Lacre de Segurança Vermelho Rolo 500 Und",
    "Papel Acoplado (500 und)",
    "Papel Acoplado Ezzepel (500 und)",
    "Papel Acoplado Laminado (200 und)",
    "Saco Kraft G 28x33 (50 Und)",
    "Saco Kraft M 24x34 (50un)",
    "Saco Kraft P 21x34 (50und)",
    "Sacola Kraft G 24X14,5X26 (50 Und)",
    "Sacola kraft GG 30X20X31 (50 Und",
    "Gordura Vegetal Coamo 14,5 Kg / 15,8 L",
    "Oleo Composto Saude 5,01 L",
    "Oleo Saude Fry 14,5 Kg / 15,8 L",
    "Avental Sorvepan 75cm X 55cm",
    "Espeto de Bambu Golf 15 cm (50 Und)",
    "Guardanapo Nobby Folha Dupla (50 Und)",
    "Luva de Nitrilo Preta G",
    "Luva de Nitrilo Preta M (100 Und)",
    "Bolinho de Carne 2 Kg (Medio)",
    "Bolinho de Queijo 2 kg (Medio)",
    "Coxinha de Frango 2 Kg (Medio)",
    "Coxinha de Frango C/ Requeijão 2 Kg (Medio)",
    "Croissant 4 queijos 1,5KG",
    "Croissant Calabresa C/Requeijão 1,5 Kg",
    "Croissant Presunto e Queijo 1,5Kg",
    "Hamburgão Queijo 1,5 Kg",
    "Mini Bolinho de Carne 1 Kg",
    "Mini Bolinho de Queijo 1 Kg",
    "Mini Coxinha de Frango 1 Kg",
    "Mini Risole de Apresuntado C/ Queijo 1 Kg",
    "Pão de Queijo C/ Frango 500g",
    "Pão de Queijo C/ Requeijão 500 g",
    "Pão de Queijo Parmesão 1 Kg",
    "Pão de Queijo Parmesão 500 g",
    "Pão de Queijo Tradicional 1 Kg",
    "Risole Presunto e Queijo 2 Kg (M)",
    "Açai Ice Mix 1 L",
    "Açai Ice Mix 10 L",
    "Açai Ice Mix 2 L",
    "Açai Ice Mix 5 L",
    "Bala de Coco Casa Maravilha 120g",
    "Batata Cebola e Salsa Boby 250g",
    "Batata Chips Sabor Queijo Nacho Gabil 180g",
    "Batata Chips Trad. Gabil 180g",
    "Batata Trad. Lisa Boby 250g",
    "Biscoito Amendoim 250g",
    "Biscoito Palito C/ Parmesão Vovo Bela 100g",
    "Biscoito Palito Escaldado Vovo Bela 100g",
    "Biscoito Polvilho C/ Queijo Vovo Bela 100g",
    "Biscoito Polvilho Sabor Cebola e Salsa Gabil 200g",
    "Biscoito Polvilho Sabor Queijo Gabil 200g",
    "Biscoito Polvilho Trad. Salgado Gabil 200g",
    "Calda Caramelo Toffee 1,01 Kg",
    "Calda Chocolate 1,01 Kg",
    "Calda Frutas Vermelhas 1,01 Kg",
    "Calda Maracuja 1,01 Kg",
    "Casadinho Goiaba Vovo Bela",
    "Chantilly Spray Polenghi 250g",
    "Creme Americano 10 L",
    "Creme Americano 7 L",
    "Creme Crocante Ovomaltine 100g",
    "Creme Crocante Ovomaltine 260g",
    "Creme Crocante Ovomaltine 530g",
    "Cx Pudim C/ Calda Rebeka 120g",
    "Doce de Leite Santa Maria 1,2 Kg",
    "Nutella 140g",
    "Nutella 350g",
    "Nutella 3Kg",
    "Nutella 650g",
    "Ovomaltine Flocos Crocante 750g",
    "Petit Gateal Doce de Leite 320g",
    "Petit Gateau 600g Cacau Belga",
    "Pudim C/ Calda Rebeka 120g",
    "Quebra Quebra Vovo Bela 250g",
    "Rosquinha Sabor Nata Vovo Bela 250g",
    "Salgadinho Sabor Bacon Vovo Bela 150g",
    "Salgadinho Sabor Churrasco Vovo Bela 150g",
    "Salgadinho Sabor Pimenta Vovo Bela 150g",
    "Suspiro Caseiro Vovo Bela 80g",
    "Suspiro Cremoso 100g",
    "Fardo Agua Cristal 510 ML (12 Uni)",
    "Fardo Agua Crystal Bio 500 ML (12 Und)",
    "Polpa Congelada de Abacaxi 100g",
    "Polpa Congelada de Açaí 100 g",
    "Polpa Congelada de Acerola 100g",
    "Fumaça líquida RN 100ml",
    "Sal Grosso Rosa Do Himalaia D’cheff 110g",
    "Tempero pra hambúrguer RN 150g",
    "Chicken Supreme 2,5KG Seara",
    "Chicken Supreme Burger 2KG Seara",
    "Hamburguer de Frango 360g Wessel (2 Und 180g)",
    "Hamburguer Bovino Niali 32x120g",
    "Hamburguer Bovino Niali 36x90g",
    "Hamburguer Brasa Trad. 120g (Und)",
    "Hamburguer Brasa Trad. 56g (Und)",
    "Hamburguer Brasa Trad. 90g (Und)",
    "Hamburguer Tradicional Brasa 30x120g",
    "Hamburguer Tradicional Brasa 36x56g",
    "Hamburguer Tradicional Brasa 36x90g",
    "Hamburguer Brasa Pic. 56g (Und)",
    "Hamburguer Brasa Pic. 90g (Und)",
    "Hamburguer Brasa Picanha 36x56g",
    "Hamburguer Picanha Brasa 30x120g",
    "Hamburguer Picanha Brasa 36x90g",
    "Hamburguer Angus Brasa 30x120g",
    "Caixa Hamburguer Wessel Bovino 120 g (48 Und)",
    "Caixa Hamburguer Wessel Costela 120 g (48 Und)",
    "Caixa Hamburguer Wessel Frango 140 g (42 Und)",
    "Caixa Hamburguer Wessel Picanha 120 g (48 Und)",
    "Hamburguer Aerki Costela 130g",
    "Hamburguer Aerki Costela 200g",
    "Hamburguer Aerki Fraldinha C/ Mussarela 220g",
    "Hamburguer Aerki Picanha 130g",
    "Hamburguer Aerki Picanha 200g",
    "Hamburguer Angus Brasa 150g (Sem Tempero)",
    "Hamburguer Bov. Wessel 120 g",
    "Hamburguer Com Costela Gourmet Brasa 150g",
    "Hamburguer Com Picanha Brasa 150g",
    "Hamburguer Costela Wessel 120 g",
    "Hamburguer Gourmet 150g Niali",
    "Hamburguer Picanha Wessel 120 g Unidade",
    "Anel de Cebola Bem Brasil 1,05 Kg",
    "Cx Anel de Cebola 1,05 Kg (6 Und)",
    "Cx Anel de Cebola Flavor 1,1 Kg (6Und)",
    "Batata Bem Brasil 9mm 2 Kg Mais Batata",
    "Batata Bem Brasil Carinhas 1,05KG",
    "Batata Bem Brasil Fast Food 2 Kg",
    "Batata Bem Brasil Uai 2 Kg",
    "Batata Crinkle 2 Kg LudiMix",
    "Batata Crinkle Bem Brasil 2 Kg",
    "Batata LambWeston 7mm 2,25KG",
    "Batata LambWeston 9mm 2,5KG",
    "Batata Rústica Ludi Mix 2 Kg",
    "Batata SteakHouse LambWeston 2,5 Kg",
    "Cx Batata Crinkle Bem Brasil 2 Kg",
    "Cx Batata Fast Food Bem Brasill 2 Kg",
    "Cx Batata LambWeston 7mm 2,25 Kg",
    "Cx Batata LambWeston 9mm 2,5 Kg",
    "Cx Batata Trad. Mais Batata 2 Kg",
    "Bacon Cubo Lactofrios 1kg",
    "Bacon Cubo Mister Beef 1kg",
    "Bacon Fat. Curatto 1 Kg",
    "Bacon Fat. Paleta Sabor Mineiro 1 Kg",
    "Bacon Fatias Mister Beef 1kg",
    "Bacon Lactofrios Fatiado 1kg",
    "Bacon Paleta Cubos FrigoLaste 1Kg",
    "Molho Ekma Hot Dog 1,02 Kg",
    "Cheddar Fatiado Madero 144 g",
    "Cheddar Sandwich Fat. Polenghi 144 g",
    "Cheddar Sandwich Fat. Polenghi 288 g",
    "Cx Queijo Cheddar Polenghi Fatiado",
    "Cx Queijo Cheddar Schreiber 2,27 Kg",
    "Cx Queijo Mussarela Polenghi Fatiado",
    "Cx Queijo Mussarela Schreiber 2,27 Kg",
    "Cx Queijo Prato Polenghi Fatiado",
    "Cx Queijo Prato Schreiber 2,27 Kg",
    "Mussarela Sandwich Fat. Polenghi 144g",
    "Prato Sandwich Fat. Polenghi 144g",
    "Queijo Cheddar Polenghi 2,27 Kg",
    "Queijo Cheddar Schreiber 2,27 Kg",
    "Queijo Coalho Artesanal de Jaguaribe 1Kg",
    "Queijo Coalho Crioulo 200g",
    "Queijo Mussarela Polenghi 2,73 Kg",
    "Queijo Mussarela Schreiber 2,27 Kg",
    "Queijo Prato Polenghi 2,73 Kg",
    "Queijo Schreiber Prato 2,27 Kg",
    "Cheddar Defumado Polenghi 1,01 Kg",
    "Cheddar Melt 1,5 Kg Molho Schreiber",
    "Cheddar Melt 400g Molho Schreiber",
    "Cheddar Polenghi Copo 200g",
    "Cheddar Vigor Molho Burger 1,5 Kg",
    "Club do Molho Polenghi Cheddar 1,5KG",
    "Clube do Molho Polenghi Cheddar 200g",
    "Cx Club do Molho Polenghi 1,05 Kg",
    "Req. Cheddar 1,5 Kg Santa Maria",
    "Requeijão Cheddar Amarilis 1,2 Kg",
    "Requeijão Cheddar Dallora 1,2 Kg",
    "Requeijão Cheddar Scala 1,5 Kg",
    "Requeijão Sabor Cheddar Polenghi 1,5 Kg",
    "American Cheese Polenghi 1,01 Kg",
    "Cream Cheese Polenghi 400 g",
    "Req. Tradicional 1,5 Kg Santa Maria",
    "Requeijão Cremoso Polenghi 1,5KG",
    "Requeijão Cremoso Scala 1,5KG",
    "Requeijão Cremoso Scala 400g",
    "Requeijão Tradicional Dallora 1,5 Kg",
    "Requeijão Tradicional Polenghi 200 g",
    "Batata Palha Boby 500 g",
    "Batata Palha Serra Mineira 500g",
    "Fardo Batata Palha Boby 500g (Promoção)",
    "Farinha Panko 1,01 Kg",
    "Farofa Bacon 350g",
    "Farofa Crocante Alho 350g",
    "Farofa Crocante Carne Seca 350g",
    "Farofa Crocante Churrasco 350g",
    "Farofa Crocante Costela 350g",
    "Farofa Crocante Costelinha com Limão 350g",
    "Farofa Crocante Frango Assado 350g",
    "Farofa Crocante Pequi 350g",
    "Farofa Crocante Picanha 350g",
    "Farofa Crocante Picante 350g",
    "Farota Crocante Churrasco 350g",
    "Milho Verde Olé 1,7 Kg",
    "Milho Verde Quero 1,7 Kg",
    "Pepino Agridoce Fat. 300g Vale Fertil",
    "Pepino Hemmer 440g Rodelas Agridoce",
    "Picles McCoys Dill Azedo 3,4 Kg",
    "Picles McCoys Dill Azedo 600 g",
    "Pimenta Biquinho 200 g Sabor Silvestre",
    "Seleta de Legumes 170g Olé",
    "Seleta de Legumes Quero 170g",
    "Seleta de Legumes em Conserva Olé 170g",
    "Ervilha em Conserva Quero 1,7 Kg",
    "Sardinha Robinson Crusoe 125g",
    "Cebola Crispy De La Marie 1,01 Kg",
    "Cebola Crispy De La Marie 500 g",
    "Cebola Caramelizada 1,01 kg Bom Principio",
    "Cebola Caramelizada 250g Liam Natural",
    "Cebola Caramelizada Defumada 1,01 Liam",
    "Cebola Caramelizada Defumada 250g Liam",
    "Cebola Caramelizada Trad. 1,01 Kg Liam",
    "Cebola Caramelizada Trad. 250g Liam",
    "Geleia Abacaxi C/Pimenta 1,01 Kg",
    "Geleia Morango Com Pimenta 250g Bom Princípio",
    "Geleia Morango C/Pimenta 1,01 Kg",
    "Geleia Pimenta Vermelha 250g",
    "Batata baby cebola salsa 250g",
    "Biscoito palito de queijo parmesão 100g",
    "Biscoito polvilho",
    "Casadinho 250g",
    "Dadinho de Tapioca 750 g",
    "Gordura saude algodão",
    "Hamburguer de Carne Bovina Carapreta 360g (2 Und)",
    "Maçarico Portatil Culinário C/Regulagem",
    "Mini Hamburguer Bovino Carapreta 360g (6 Und 60g)",
    "Molho chick Pil 1,1 kg RN - Bom Sabor",
    "Molho Yakissoba 500 ML Cepera",
    "Palito Escaldado 100g",
    "Refil Gás p/ Maçarico 227g Campgás",
    "Rosquinha nata 250g",
    "Ketchup Heinz Curry 397g",
    "Molho Tártaro kisabor 1,05kg",
]
